### ISSUE TITLE
Documentation should be updated to match new zenburn-override-colors-alist customizable functionality

### ISSUE THREAD

**Issue by juristi** [bbatsov/zenburn-emacs#302]
The change in commit 4b3e541 changed the `zenburn-override-colors-alist` to a customizable variable. This means that the way to override colours as described in the documentation does no longer work:
```elisp
(defvar zenburn-override-colors-alist
  '(("zenburn-bg+05" . "#282828")
    ("zenburn-bg+1"  . "#2F2F2F")
    ("zenburn-bg+2"  . "#3F3F3F")
    ("zenburn-bg+3"  . "#4F4F4F")))
```
The same functionality with new implementation could probably be accomplished by using `customize-set-variable` instead:
```elisp
(customize-set-variable 'zenburn-override-colors-alist
  '(("zenburn-bg+05" . "#282828")
    ("zenburn-bg+1"  . "#2F2F2F")
    ("zenburn-bg+2"  . "#3F3F3F")
    ("zenburn-bg+3"  . "#4F4F4F")))
```
Another alternative could be to change the new customize functionality into an additional feature with a slightly different name while still preserving the old `defvar` configuration option. That way the all the existing users' configurations would still continue to work.

**Comment by basil-conto** [comment]
It is wrong to suggest that users call `defvar` before loading `zenburn-theme` to begin with; that is the true bug here. `defvar` is for package authors to declare variables and assign them a default value if they happen to be void. Users have the customize interface, `setq`, `setq-default`, etc. through which to *set*, not *declare* their preferred settings.

**Comment by felixc** [comment]
Thanks for the review on the PR, @basil-conto!

I think it would be ideal in the longer run to address this issue by detecting if the user has already set the variable with `defvar`, and if so, warning them to switch to `setq`. It may have been a bug to use `defvar` in the first place, but it was recommended in the docs to people who are now using it and whose configs broke as a result of the change.

Any ideas on how one might make the switch more graceful?

**Comment by basil-conto** [comment]
> I think it would be ideal in the longer run to address this issue by detecting if the user has already set the variable with `defvar`, and if so, warning them to switch to `setq`.

FWIW, I think this is outside of the scope of `zenburn-emacs` specifically, and most Emacs packages generally. This kind of reflection/introspection should be left up to packages which care about the distinction between bound/unbound/set/customised/etc. symbols, such as the built-in `custom.el`, which provides the macro `defcustom`.

There are many popular Emacs packages which give sample setup instructions which do not universally work for all users and configurations. That is not the end of the world, because they are just **sample** instructions. There is a plethora of documentation and Q&A available in the wild which instructs both power- and non-power-users on different ways to specify values and customisations in their initialisation. The onus ultimately lies on them to figure out what they need to put in their initialisation files for their setup to work for them, or at least to ask for help with this.

> it was recommended in the docs to people who are now using it and whose configs broke as a result of the change

Here is why I think the effect of the change is far less severe then this issue makes it out to be:
* The current `defvar`-before-`load-theme` in the README is effectively the same as calling `setq`-before-`load-theme`. The user must be doing something else incorrectly for the `defvar` to break their configuration.
* If the user is doing something else wrong, it is up to them to figure out why and how to fix it, either on their own or by asking for help.
* There have been no other reports about this issue.

If there is some other justification for this fear of breaking configs which I am missing, the standard route is to announce the change somewhere and possibly accompany it with a version bump.

Don't forget that `zenburn-emacs` is a [custom theme](https://www.gnu.org/software/emacs/manual/html_node/emacs/Custom-Themes.html), not a package, and, as such, should strive to remain as programmatically simple as reasonably possible.

**Comment by felixc** [comment]
> FWIW, I think this is outside of the scope of zenburn-emacs specifically, and most Emacs packages generally. This kind of reflection/introspection should be left up to packages which care about the distinction between bound/unbound/set/customised/etc. symbols, such as the built-in custom.el, which provides the macro defcustom.

I'm not suggesting a general feature for all time, rather a band-aid for a break in the public interface. I don't think this is a general problem that other packages are likely to have, so the fix belongs here (if it is to exist at all).

> There are many popular Emacs packages which give sample setup instructions which do not universally work for all users and configurations.

This seems to affect the most basic and standard configuration; it's not about edge cases.

> That is not the end of the world, because they are just sample instructions. There is a plethora of documentation and Q&A available in the wild which instructs both power- and non-power-users on different ways to specify values and customisations in their initialisation. The onus ultimately lies on them to figure out what they need to put in their initialisation files for their setup to work for them, or at least to ask for help with this.

I disagree; I think it's a bad thing if the suggested way of using things doesn't work; and if the way that *did* work in the past is changed out unannounced.

> The current defvar-before-load-theme in the README is effectively the same as calling setq-before-load-theme. The user must be doing something else incorrectly for the defvar to break their configuration.

My configuration for this package consisted of literally just the `defvar` and then loading it, so I believe it's more common than you think, and doesn't require any other misconfiguration.

>I f the user is doing something else wrong, it is up to them to figure out why and how to fix it, either on their own or by asking for help.

Making it easier to understand where the problem is is not contrary to this. My suggestion is about getting users to the point where they know what/why changed, so they can either figure out the fix on their own, check available documentation, or ask a good targeted question. I think that's a more valuable use of everyone's time than each user starting from scratch and either spending time on understanding what happened, or having to ask someone else and have people here answer the same question repeatedly.

> There have been no other reports about this issue.

I'm not sure how we can count the number of people who came to the repo, saw this issue, fixed it locally, and quietly moved on — or the number of users who just couldn't be bothered to figure out why things broke and just left things as they were.

> If there is some other justification for this fear of breaking configs which I am missing, the standard route is to announce the change somewhere and possibly accompany it with a version bump.

Agreed; but in this case the change that broke configs already happened, and I can't see it in any changelog or similar place. That's why this bug was opened: because existing working configurations silently broke.

> Don't forget that zenburn-emacs is a custom theme, not a package, and, as such, should strive to remain as programmatically simple as reasonably possible.

I'd argue we should also always strive to be helpful to users and guide them through breaking changes.

**Comment by basil-conto** [comment]
Here's a recipe showing the currently documented `defvar` approach in action:

1. Start `emacs -Q` from the top level of the `zenburn-emacs` repository (i.e. `default-directory` is `"/path/to/zenburn-emacs/"`).
2. ```el
   (progn
     (defvar zenburn-override-colors-alist '(("zenburn-bg" . "#000000")))
     (let ((custom-theme-directory default-directory))
       (load-theme 'zenburn t)))
   ```
3. <kbd>C-j</kbd>
4. Voilà - your background is now black.

<kbd>M-x</kbd>`emacs-version`<kbd>RET</kbd> reports:

    GNU Emacs 27.0.50
    (build 2, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
    of 2018-04-26

Also reproducible on Emacs 24.5.1, 25.2.1, and Emacs 26.1 RC1.

**Comment by juristi** [comment]
Recipe to reproduce the problem. Use this simple init.el file:
```lisp
(package-initialize)
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)
(package-refresh-contents)
(unless (package-installed-p 'zenburn-theme)
  (package-install 'zenburn-theme))

(defvar zenburn-override-colors-alist
  '(("zenburn-bg" . "#000000")))
(load-theme 'zenburn t)
```
The background color is not changed.

After digging a bit further into the problem, the missing piece of information was actually that the defvar must come before the `(package-initialize)` call. I tried the Zenburn theme only after it had switched to customize, so the problem may have existed earlier and the instructions lacking already longer time.

Anyway it's good that the documentation gets an update regarding this. At the time it took a while to figure out why the colours customized in the init file did not work even though I had followed the instructions exactly as given.
